### ISSUE TITLE
Fortran optimization flags

### ISSUE THREAD

**Issue by ivan-pi** [PIK-ICoNe/NetworkDynamicsBenchmarks#1]
Hello,

it seems that the `fpm` build options you are using do not include optimization flags (see https://github.com/fortran-lang/benchmarks/issues/5#issuecomment-808929152).

Unfortunately, `fpm` doesn't yet allow custom build profiles, but I do think the latest version (written in Fortran) has a `--release` flag, which will add at least some optimization flags.

**Comment by ivan-pi** [comment]
Concerning the Fortran ODE solver interface, you could perhaps borrow some elements from the refactored `dop853` code: https://github.com/jacobwilliams/dop853

**Comment by Lima-Lima** [comment]
Thanks for the issue ivan-pi. I think a unified ODE solver interface in F2003 for (at least) Hairer's suite would be very useful, but wasn't a goal for this little project. I had considered mirroring jacob's `dop853` for `dopri`, but decided not to undertake that for this one-off script. 

Regarding optimization flags, the fortran program was built with:

`-03 -march=native -ffast-math -funroll-all-loops`

Thank you very much for taking a look at this repo and providing advice on fpm. Pull requests to the fortran benchmark program are also very welcome. It's got some warts but I would be (pleasantly) surprised to see significant performance improvements.

**Comment by Lima-Lima** [comment]
@lindnemi Could you close this issue? Optimizations flags were used.
